server:
  port: 11530

localhost: 43.142.146.75

spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${localhost}:3306/tjut-wall-user-server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: user
    password: user
  redis:
    host: ${localhost}
    port: 6379
    password: 123456
    connect-timeout: 10000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: ${localhost}
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  cloud:
    nacos:
      server-addr: ${localhost}:8848


feign:
  client:
    config:
      default:
        loggerLevel: full

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.sipc.mmtbackend.mapper: debug