server:
  port: 11530

localhost: 43.142.146.75
nacos-server: 43.143.162.177:8849

spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${localhost}:3306/tjut_wall_user_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: user
    password: user
  redis:
    host: ${localhost}
    port: 6379
    password: 123456
    connect-timeout: 10000
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  rabbitmq:
    host: ${localhost}
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
  cloud:
    nacos:
      server-addr: ${nacos-server}
#      discovery:
#        ip: 43.142.146.75
#        port: 11530

feign:
  client:
    config:
      default:
        loggerLevel: full

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.sipc.mmtbackend.mapper: debug

minio:
  endpoint: http://www.haorui.xyz:19000 #Minio服务所在地址
  bucketName: palzoo #存储桶名称
  accessKey: palzoo #访问的key
  secretKey: PalzooPass #访问的秘钥