server:
  port: 11500

localhost: localhost

remote-host: 43.142.146.75

spring:
  application:
    name: control-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${remote-host}/tjut_wall_login_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: user
    password: user
  redis:
    url: redis://root@${remote-host}:6379
    connect-timeout: 10000
  cloud:
    nacos:
      server-addr: ${remote-host}:8848

feign:
  client:
    config:
      default:
        loggerLevel: full

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
