server:
  port: 11500

localhost: localhost
nacos-server: 43.143.162.177:8849

remote-host: 43.142.146.75

spring:
  application:
    name: control-server
  redis:
    url: redis://root@${remote-host}:6379
    connect-timeout: 10000
  cloud:
    nacos:
      server-addr: ${nacos-server}

feign:
  client:
    config:
      default:
        loggerLevel: full

