server:
  port: 11510

localhost: localhost

remote-host: 43.142.146.75

spring:
  application:
    name: login-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${remote-host}/tjut_wall_login_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: user
    password: user
  redis:
    url: redis://root@${localhost}:6379
    connect-timeout: 10000
  cloud:
    nacos:
      server-addr: ${remote-host}:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

wechat:
  appId: wx9a3b6323352027a1
  appSecret: 2bd4c9a11a48eb44735a46f71f09ed02
