server:
  port: 11540

remote-host: 43.142.146.75

spring:
  application:
    name: chat-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${remote-host}/tjut_wall_chat_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: user
    password: user
  redis:
    url: redis://root@localhost:6379
    connect-timeout: 10000
  cloud:
    nacos:
      server-addr: 43.143.162.177:8849

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sipc.chatserver.pojo.domain
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    cache-enabled: true
